image: debian:stretch-slim

stages:
  - test
  - review
  - deploy

variables:
  GIT_SUBMODULE_STRATEGY: recursive

.ssh_setup: &SSH_SETUP |
  apt-get update && apt-get install -y --no-install-recommends openssh-client rsync

  echo "${SSH_PRIVATE_KEY}" > id_rsa
  chmod 700 id_rsa
  mkdir -p ~/.ssh
  echo "${SSH_HOST_KEY}" > ~/.ssh/known_hosts

.install_make: &INSTALL_MAKE |
  apt-get update && apt-get install -y --no-install-recommends make

test:
  before_script:
    - *INSTALL_MAKE
  script:
    - make build-conf
    - ./binaries/hugo --theme coder
  except:
    - master

review:
  stage: review
  before_script:
    - *INSTALL_MAKE
    - *SSH_SETUP
  script:
    - make build-conf
    - ./binaries/hugo --theme coder --baseURL https://review.khosrow.io --buildDrafts
    - rsync -hrvz --delete --exclude=_ -e 'ssh -i id_rsa' public/ publisher@khosrow.io:/srv/nginx/khosrow.io/review
  environment:
    name: review
    url: https://review.khosrow.io
  only:
    - branches
  except:
    - master

deploy:
  stage: deploy
  before_script:
    - *INSTALL_MAKE
    - *SSH_SETUP
  script:
    - apt-get update && apt-get install -y --no-install-recommends make
    - make build-conf
    - ./binaries/hugo --theme coder
    - rsync -hrvz --delete --exclude=_ -e 'ssh -i id_rsa' public/ publisher@khosrow.io:/srv/nginx/khosrow.io/public
  environment:
    name: production
    url: https://khosrow.io
  only:
    - master
