image: registry.gitlab.com/pages/hugo:latest

test:
  script:
    - hugo
  except:
    - master

deploy:
  stage: deploy
  before_script:
    - apk --update add --no-cache openssh rsync
    - hugo -t coder
  script:
    - echo "${SSH_PRIVATE_KEY}" > id_rsa
    - chmod 700 id_rsa
    - mkdir "${HOME}/.ssh"
    - echo "${SSH_HOST_KEY}" > "${HOME}/.ssh/known_hosts"
    - rsync -hrvz --delete --exclude=_ -e 'ssh -i id_rsa' public/ publisher@khosrow.io:/srv/nginx/khosrow.io/public
  environment:
    name: production
    url: https://khosrow.io
  only:
    - master

pages:
  script:
    - hugo -t coder
  artifacts:
    paths:
    - public
  only:
  - master
