image: registry.gitlab.com/pages/hugo:latest

test:
  script:
    - hugo
  except:
    - master

deploy:
  stage: deploy
  before_script:
    - apk update
    - apk add ssh rsync
    - echo "Build with hugo" #hugo -t creative
  script:
    - echo "${SSH_PRIVATE_KEY}" > id_rsa
    - chmod 700 id_rsa
    - mkdir "${HOME}/.ssh"
    - echo "${SSH_HOST_KEY}" > "${HOME}/.ssh/known_hosts"
    - rsync -hrvz --delete --exclude=_ -e 'ssh -i id_rsa' public/ root@khosrow.io:/srv/nginx/khosrow.io/public
  environment:
    name: production
    url: https://khosrow.io
  only:
    - master


