image: alpine:latest
#image: registry.gitlab.com/pages/hugo:latest

test_site:
  script:
    - hugo
  except:
    - master

deploy_prod:
  stage: deploy
  script:
    - rsync -av --delete public /srv/nginx/khosrow.io/public
  environment:
    name: production
    url: https://khosrow.io
  only:
    - master


