image: registry.gitlab.com/khosrow.io/ci-tools

stages:
  - deploy

variables:
  GIT_SUBMODULE_STRATEGY: recursive

review:
  stage: deploy
  script:
    - make build -- --buildDrafts --baseURL https://review.khosrow.io
    - rsync -hrvz --delete --exclude=_ -e 'ssh -i ~/.ssh/id_rsa' public/ publisher@khosrow.io:/srv/nginx/khosrow.io/review
  environment:
    name: review
    url: https://review.khosrow.io
  only:
    - branches
  except:
    - master

live:
  stage: deploy
  script:
    - make build
    - rsync -hrvz --delete --exclude=_ -e 'ssh -i ~/.ssh/id_rsa' public/ publisher@khosrow.io:/srv/nginx/khosrow.io/public
  environment:
    name: production
    url: https://khosrow.io
  only:
    - master
