baseurl = "https://khosrow.io"
title = "Khosrow.io"
theme = "coder"
languagecode = "en"

paginate = 20
canonifyurls = true
googleAnalytics = "UA-115461719-1"

[params]
    author = "Khosrow Moossavi"
    description = "My name is Khosrow Moossavi, I'm a Cloud Native DevOps and Rock Climber."
    keywords = "khosrow,moossavi,personal,java,developer,architect,devops,blog"
    info = "Cloud Native DevOps, Rock Climber"

    hideCopyright = false
    hideCopyrightOwner = false
    hideCredits = false

    # Custom CSS
    custom_css = ["css/style-all.min.css", "css/fontawesome-all.min.css"]

    # Twitter Cards
    images = ["images/avatar.png"]
    [social]
        twitter = "khos2ow"

[[params.social]]
    name = "Email"
    weight = 1
    type = "r"
    icon = "envelope"
    url = "mailto:me@khosrow.io"
[[params.social]]
    name = "Github"
    weight = 2
    type = "b"
    icon = "github"
    url = "https://github.com/khos2ow/"
[[params.social]]
    name = "Gitlab"
    weight = 3
    type = "b"
    icon = "gitlab"
    url = "https://gitlab.com/khos2ow/"
[[params.social]]
    name = "Docker Hub"
    weight = 4
    type = "b"
    icon = "docker"
    url = "https://hub.docker.com/u/khos2ow"
[[params.social]]
    name = "Twitter"
    weight = 5
    type = "b"
    icon = "twitter"
    url = "https://twitter.com/khos2ow/"
[[params.social]]
    name = "LinkedIn"
    weight = 6
    type = "b"
    icon = "linkedin"
    url = "https://linkedin.com/in/khosrowmoossavi/"
[[params.social]]
    name = "Stack Overflow"
    weight = 7
    type = "b"
    icon = "stack-overflow"
    url = "https://stackoverflow.com/users/493615/khosrow"

[[menu.main]]
    name = "About"
    weight = 1
    url = "/about/"
