
# === Farsi ===
[languages.fa]
  title        = "خسرو.آی‌او"
  weight       = 2
  languageCode = "fa"
  languageName = "فارسی"

[languages.fa.params]
  langcode    = "fa"
  author      = "خسرو موسوی"
  description = "من خسرو موسوی هستم. Cloud Native دواپس و سنگ‌نورد."
  keywords    = "خسرو,موسوی,شخصی,جاوا,برنامه‌نویس,دواپس,معمار,بلاگ"
  info        = "Cloud Native دواپس، سنگ‌نورد"
  rtl         = true

[languages.fa.params.copyright]
  year        = "۱۳۹۷"
